<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <DefaultClrNameSpace>Microsoft.Samples.ColorPickerExample</DefaultClrNameSpace>
    <TargetType>library</TargetType>
    <Configuration>Release</Configuration>
    <BuildSystem>MSBuild</BuildSystem>
    <RootNamespace>Samples.ColorPicker</RootNamespace>
    <StartupObject></StartupObject>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <CodeAnalysisRules></CodeAnalysisRules>
  </PropertyGroup>
</Project>